name: Download Roblox Installer

on:
  workflow_dispatch:
  repository_dispatch:
    types: [install-roblox]

jobs:
  download_roblox_installer:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download Roblox Installer
      run: Invoke-WebRequest -Uri "https://setup.rbxcdn.com/RobloxPlayerLauncher.exe" -OutFile "RobloxInstaller.exe"

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: roblox-installer
        path: RobloxInstaller.exe

    - name: Provide Download Link
      run: echo "Download the Roblox installer from the Artifacts section in the Actions tab."

    - name: Prompt User for Download
      run: |
        $response = Read-Host "Do you want to download the Roblox Installer? (yes/no)"
        if ($response -eq "yes") {
          Invoke-WebRequest -Uri "https://setup.rbxcdn.com/RobloxPlayerLauncher.exe" -OutFile "RobloxInstaller.exe"
          Write-Host "Roblox Installer has been downloaded."
        } else {
          Write-Host "Download cancelled by user."
        }
