name: Download Roblox Installer

on:
  workflow_dispatch:
  repository_dispatch:
    types: [install-roblox]  # Allows frontend to trigger this

jobs:
  download_roblox_installer:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download Roblox Installer
      run: Invoke-WebRequest -Uri "https://setup.rbxcdn.com/RobloxPlayerLauncher.exe" -OutFile "RobloxInstaller.exe"

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: roblox-installer
        path: RobloxInstaller.exe
